name: Build and Test
on: [push, pull_request]
jobs:
  windows:
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
          version: ['8.0', '8.1', '8.2', '8.3']
          arch: [x64, x86]
          ts: [ts]
    runs-on: windows-2019
    steps:
      - name: Checkout xmlrpc
        uses: actions/checkout@v4
      - name: Setup PHP
        id: setup-php
        uses: php/setup-php-sdk@v0.8
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
          ts: ${{matrix.ts}}
          deps: libiconv, libxml2
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.setup-php.outputs.toolset}}
      - name: phpize
        run: phpize
      - name: configure
        run: configure --with-xmlrpc --with-prefix=${{steps.setup-php.outputs.prefix}}
      - name: make
        run: nmake
      - name: test
        run: nmake test TESTS="--show-diff tests"
